version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf

python:
  install:
    - requirements: docs/source/requirements.txt
