

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    
sphinx:
  configuration: source/conf.py

formats:
   - pdf

python:
   install:
   - requirements: source/requirements.txt
  
