"""
Requirements file management for package pinning and export.
"""

import os
import sys
import subprocess
import json
from typing import List, Dict, Optional
from datetime import datetime


class RequirementsManager:
    """Manage requirements.txt creation and package pinning."""
    
    def __init__(self, pip_command=None):
        self.pip_command = pip_command or [sys.executable, '-m', 'pip']
    
    def get_installed_packages_with_versions(self) -> List[Dict[str, str]]:
        """Get all installed packages with their versions."""
        packages = []
        try:
            result = subprocess.run(
                self.pip_command + ['list', '--format=json'],
                capture_output=True,
                text=True,
                timeout=30
            )
            if result.returncode == 0:
                packages = json.loads(result.stdout)
        except Exception:
            # Fallback to freeze
            try:
                result = subprocess.run(
                    self.pip_command + ['freeze'],
                    capture_output=True,
                    text=True,
                    timeout=30
                )
                if result.returncode == 0:
                    for line in result.stdout.splitlines():
                        if '==' in line and not line.startswith('#'):
                            name, version = line.split('==', 1)
                            packages.append({'name': name.strip(), 'version': version.strip()})
            except Exception:
                pass
        
        return packages
    
    def export_requirements(
        self,
        output_path: str,
        packages: Optional[List[str]] = None,
        include_dependencies: bool = True,
        add_header: bool = True
    ) -> bool:
        """
        Export packages to a requirements.txt file.
        
        Args:
            output_path: Path to save the requirements file
            packages: Specific packages to export (None = all installed)
            include_dependencies: Whether to include all dependencies
            add_header: Add a header comment with generation info
        
        Returns:
            True if successful, False otherwise
        """
        try:
            lines = []
            
            if add_header:
                lines.append(f"# Generated by PYMODINS on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
                lines.append(f"# Python {sys.version.split()[0]}")
                lines.append("")
            
            if packages:
                # Export only specific packages
                installed = {pkg['name'].lower(): pkg for pkg in self.get_installed_packages_with_versions()}
                
                for pkg_name in packages:
                    pkg_lower = pkg_name.lower()
                    if pkg_lower in installed:
                        pkg_info = installed[pkg_lower]
                        lines.append(f"{pkg_info['name']}=={pkg_info['version']}")
                    else:
                        # Package not installed, add without version
                        lines.append(pkg_name)
            else:
                # Export all packages
                if include_dependencies:
                    # Use pip freeze for full dependency tree
                    result = subprocess.run(
                        self.pip_command + ['freeze'],
                        capture_output=True,
                        text=True,
                        timeout=30
                    )
                    if result.returncode == 0:
                        for line in result.stdout.splitlines():
                            if line and not line.startswith('#'):
                                # Filter out editable installs and local paths
                                if not line.startswith('-e') and '@ file://' not in line:
                                    lines.append(line)
                else:
                    # List only top-level packages
                    all_packages = self.get_installed_packages_with_versions()
                    for pkg in sorted(all_packages, key=lambda x: x['name'].lower()):
                        lines.append(f"{pkg['name']}=={pkg['version']}")
            
            # Write to file
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines))
                if lines:
                    f.write('\n')  # Final newline
            
            return True
        
        except Exception as e:
            print(f"Error exporting requirements: {e}")
            return False
    
    def install_from_requirements(self, requirements_path: str) -> tuple[bool, str]:
        """
        Install packages from a requirements.txt file.
        
        Returns:
            Tuple of (success, output_message)
        """
        if not os.path.isfile(requirements_path):
            return False, f"Requirements file not found: {requirements_path}"
        
        try:
            result = subprocess.run(
                self.pip_command + ['install', '-r', requirements_path],
                capture_output=True,
                text=True,
                timeout=600  # 10 minutes timeout for large files
            )
            
            success = result.returncode == 0
            output = result.stdout + result.stderr
            
            return success, output
        
        except subprocess.TimeoutExpired:
            return False, "Installation timed out (exceeded 10 minutes)"
        except Exception as e:
            return False, f"Error installing from requirements: {e}"
    
    def pin_package_version(self, package_name: str) -> Optional[str]:
        """
        Get the pinned version string for a package (e.g., 'numpy==1.21.0').
        
        Returns:
            Pinned requirement string or None if not installed
        """
        installed = self.get_installed_packages_with_versions()
        pkg_lower = package_name.lower()
        
        for pkg in installed:
            if pkg['name'].lower() == pkg_lower:
                return f"{pkg['name']}=={pkg['version']}"
        
        return None
    
    def generate_requirements_from_category(
        self,
        category_name: str,
        modules: List[str],
        output_path: str
    ) -> bool:
        """
        Generate a requirements file for a specific category of modules.
        
        Args:
            category_name: Name of the category
            modules: List of module names in the category
            output_path: Path to save the requirements file
        
        Returns:
            True if successful, False otherwise
        """
        try:
            lines = [
                f"# PYMODINS - {category_name}",
                f"# Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                f"# Python {sys.version.split()[0]}",
                "",
            ]
            
            installed = {pkg['name'].lower(): pkg for pkg in self.get_installed_packages_with_versions()}
            
            found_count = 0
            not_found = []
            
            for module in modules:
                module_lower = module.lower()
                if module_lower in installed:
                    pkg_info = installed[module_lower]
                    lines.append(f"{pkg_info['name']}=={pkg_info['version']}")
                    found_count += 1
                else:
                    not_found.append(module)
            
            if not_found:
                lines.append("")
                lines.append("# Not currently installed:")
                for module in not_found:
                    lines.append(f"# {module}")
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines))
                f.write('\n')
            
            return True
        
        except Exception as e:
            print(f"Error generating category requirements: {e}")
            return False
    
    def compare_requirements(self, requirements_path: str) -> Dict[str, Dict]:
        """
        Compare a requirements file with currently installed packages.
        
        Returns:
            Dict with 'missing', 'outdated', 'extra' keys
        """
        result = {
            'missing': [],      # In file but not installed
            'outdated': [],     # Installed but different version
            'extra': [],        # Installed but not in file
            'matching': []      # Exact matches
        }
        
        if not os.path.isfile(requirements_path):
            return result
        
        try:
            # Parse requirements file
            required = {}
            with open(requirements_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#'):
                        if '==' in line:
                            name, version = line.split('==', 1)
                            required[name.strip().lower()] = version.strip()
            
            # Get installed packages
            installed = {pkg['name'].lower(): pkg['version'] 
                        for pkg in self.get_installed_packages_with_versions()}
            
            # Compare
            for req_name, req_version in required.items():
                if req_name not in installed:
                    result['missing'].append(f"{req_name}=={req_version}")
                elif installed[req_name] != req_version:
                    result['outdated'].append({
                        'package': req_name,
                        'required': req_version,
                        'installed': installed[req_name]
                    })
                else:
                    result['matching'].append(req_name)
            
            # Find extra packages
            for inst_name in installed:
                if inst_name not in required:
                    result['extra'].append(f"{inst_name}=={installed[inst_name]}")
        
        except Exception as e:
            print(f"Error comparing requirements: {e}")
        
        return result
